services:
  patient-service-db:
    image: postgres:16
    container_name: patient-service-db
    ports:
      - "5001:5432"
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal

  patient-service:
    build: .
    container_name: patient-service
    ports:
      - "4000:4000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://patient-service-db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - patient-service-db
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  pgdata: